
# Labels to add to all resources and selectors.
commonLabels:
  app.kubernetes.io/name: ocs-client-operator-console

resources:
- console_init.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ocs-client-operator-console
  newName: quay.io/jarrpa/ocs-client-console
  newTag: latest
namePrefix: ocs-client-operator-
